install.packages("shiny")
install.packages("shinythemes")
install.packages("tidyverse")
install.packages("cowplot")
install.packages("colourpicker")
install.packages("viridis")
install.packages("plotly")